[server]
port = 8081
threads = 32

[general]
version = 1 # The coordinator version

last_seen_timeout = 60 # How many seconds without getting a ping before we assume this worker died

trust_count = 3 # How many workers need to download the same chunk before we trust that it is accurate

[paths]
chunk_temp_path = "/staging/temp"
storage_path = "/stating"